### ISSUE TITLE
Fuzzy preview of elements in stencil in OmniGraffle?

### ISSUE THREAD

**Issue by ringods** [m-radzikowski/omnigraffle-stencil#2]
Hello,

Thanks for your conversion script. I tried it out this afternoon here:

https://github.com/ringods/OmniGraffle-AREI-Stencil

I added the created stencil file to my OmniGraffle 7.18.2 but the preview of the symbols all look fuzzy. The individual PDF files for each symbol within the stencil are top quality. 

<img width="869" alt="Screenshot 2021-01-31 at 22 04 09" src="https://user-images.githubusercontent.com/77923/106398150-809e1f00-6411-11eb-95f3-777c2b8c0622.png">

The left side of the image shows the PDF of one symbol in `Preview`, the right side is how it is displayed in the stencil preview of OmniGraffle.

Is there any way to have it previewed in higher quality?

**Comment by m-radzikowski** [comment]
Hey. I did not observe such behavior before. And when you put the image from stencil on the diagram, is it ok?

The repo you linked is either removed or private, so I don't see it. If you share with me at least a single icon (as svg) I will try to reproduce it and see what can be done with it.

**Comment by ringods** [comment]
@m-radzikowski I made the project public. The README contains 3 commands for you to replicate the full stencil.

**Comment by m-radzikowski** [comment]
Hey, sorry for the late reply. It looks like OmniGraffle does a pretty bad job displaying previews of small images, despite them being vector graphics. And all your source SVGs are pretty small - between 9 and 30 pixels.

When I increased the SVG image size (just manually changed `width` and `height` attributes of root `<svg>`) the previews in OmniGraffle were clear and sharp. Of course, it resulted with also bigger images being inserted from the stencil into the canvas.

The easiest thing you can do is to upscale all SVG files before creating a stencil. It can be done with some svg conversion tools, like [the one described here](https://graphicdesign.stackexchange.com/questions/6574/in-inkscape-resize-both-the-document-and-its-content-at-the-same-time/6670#6670). Upscale SVGs, either times X if you want the images to be proportional to each other or just make them all 50x50 px or something like that.

I don't see a point in adding upscaling behavior to my tool since this can be done with external tools, depending on specific needs.

Also, to create the stencil, you don't need to fetch my whole repo and use poetry to run it, you can just install it with pip: `pip3 install omnigraffle-stencil`.

Let me know if you have further questions.
